---
  - name: Install java package
    yum: name={{ item }} state=present
    with_items:
     - java-1.8.0-openjdk
    when: 
     - ansible_os_family == "CentOS"
  
  - name: Configure JAVA_HOME envriment
    lineinfile: dest=/etc/profile line='export JAVA_HOME=/usr/estuary/packages/openjdk-1.8.0/jdk8u-server-release-1609' insertafter='EOF'
    
  - name: Configure JAVA_CLASS envriment
    lineinfile: dest=/etc/profile line='export CLASSPATH=$JAVA_HOME/lib' insertafter='EOF'
    
  - name: Add to path envriment
    lineinfile: dest=/etc/profile line='export PATH=$PATH:$JAVA_HOME/bin' insertafter='EOF'

  - name: Create test dir
    file: path={{test_dir}} state=directory mode=0755

  - name: copy SPECJVM2008 to dest
    copy: src=SPECjvm2008.tar.gz dest={{test_dir}}/ mode=0755
  
  - name: Install SPECJVM2008
    unarchive: src={{test_dir}}/SPECjvm2008.tar.gz dest=/ copy=no
  
  - name: Do SPECJVM2008 test
    command: java -jar SPECjvm2008.jar -Dspecjvm.result.dir={{test_dir}}/results --base
