---
  - name: Install java package when OS == CentOS
    yum: name={{ item }} state=present
    with_items:
      - java-1.8.0-openjdk
    when: 
      - ansible_os_family == "RedHat"

  - name: Install java package when OS == Debian
    apt: name={{ item }} state=present
    with_items:
      - openjdk-8-jdk 
      - openjdk-8-jre
      #- libfreetype-dev 
      #- fontconfig-dev
    when: 
      - ansible_os_family == "Debian"
  
  - name: Create test dir
    file: path=/usr/local/benchmark/specjvm state=directory mode=0755

  - name: downlaod SPECJVM2008 to dest
    get_url:
      url: ftp://ftp:123456@htsat.vicp.cc/SPECjvm2018_2_01_setup.jar
      dest: /usr/local/benchmark/specjvm
      mode: 0755
  
  - name: Install SPECJVM2008
    unarchive: 
      src: /usr/local/benchmark/specjvm/SPECjvm2018_2_01_setup.jar 
      dest: /usr/local/benchmark/specjvm 
      copy: no
  
  - name: Do SPECJVM2008 test for Redhat - 1
    copy: src=env_ubuntu.sh dest=/usr/local/benchmark/specjvm
    when:
      - ansible_os_family == "RedHat"

  - name: Do SPECJVM2008 test for Redhat - 2 
    command: sh env_centos.sh  
    args:
      chdir: /usr/local/benchmark/specjvm
    when:
      - ansible_os_family == "RedHat"
 
  - name: Do SPECJVM2008 test for Debian - 1
    copy: src=env_ubuntu.sh dest=/usr/local/benchmark/specjvm
    when:
      - ansible_os_family == "Debian"

  - name: Do SPECJVM2008 test for Debian - 2
    command: sh env_ubuntu.sh  
    args:
      chdir: /usr/local/benchmark/specjvm
    when:
      - ansible_os_family == "Debian"





